---

init:
  - set PATH=C:\Python27\Scripts;%PATH%             # while python's bin is already in PATH, but pip.exe in Scripts\ dir isn't
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  # Python doesn't seem to be able to import files from the current script's
  # directory on Windows.
  - set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%\test

install:
  - git submodule update --init

environment:
  JOBS: 3
  matrix:
  - GENERATOR: MSYS Makefiles
    CONFIG: Release
    TARGET: x86
    JOBS_FLAG: -j
    MSVC_FLAG:
    EXE_DIR: .
    DEPLOY: false
  - GENERATOR: Visual Studio 14 2015
    CONFIG: Release
    TARGET: x86
    JOBS_FLAG: "/m:"
    MSVC_FLAG: --msvc
    EXE_DIR: '%CONFIG%'
    DEPLOY: true
    DEPLOY_NAME: wabt-%APPVEYOR_REPO_TAG_NAME%-win32.zip
  - GENERATOR: Visual Studio 14 2015 Win64
    CONFIG: Debug
    TARGET: x86_amd64
    JOBS_FLAG: "/m:"
    MSVC_FLAG: --msvc
    EXE_DIR: '%CONFIG%'
    DEPLOY: false
  - GENERATOR: Visual Studio 14 2015 Win64
    CONFIG: Release
    TARGET: x86_amd64
    JOBS_FLAG: "/m:"
    MSVC_FLAG: --msvc
    EXE_DIR: '%CONFIG%'
    DEPLOY: true
    DEPLOY_NAME: wabt-%APPVEYOR_REPO_TAG_NAME%-win64.zip

build_script:
  - cmake .  -DCMAKE_BUILD_TYPE=%CONFIG% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER% -G "%GENERATOR%"
  - cmake --build . --config %CONFIG% --target install -- %JOBS_FLAG%%JOBS%

test_script:
  - call scripts\appveyor-test-script.bat

# Must happen before artifacts step.
after_test:
  - call scripts\appveyor-after-test.bat

artifacts:
  - path: "%DEPLOY_NAME%"
    name: wabt
  - path: "%DEPLOY_NAME%.sha256"
    name: sha256

deploy:
  description: 'wabt release'
  provider: GitHub
  auth_token:
    secure: lHQSdycL1FHsFKZZ0RSnYSUtRitYaLb4uxDjCSOpYHnk4gIO/0/DLu4aoU2VvD7Y
  artifact: wabt,sha256
  on:
    appveyor_repo_tag: true
    deploy: true
