[package]
name = "wabt"
version = "1.0.12"
description = "The WebAssembly Binary Toolkit"
readme = "README-wapm.md"
repository = "https://github.com/wapm-packages/wabt"

[[module]]
name = "wat2wasm"
source = "out/wasi/wat2wasm.wasm"
abi = "wasi"
interfaces = {wasi= "0.0.0-unstable"}

[[module]]
name = "wast2json"
source = "out/wasi/wast2json.wasm"
abi = "wasi"
interfaces = {wasi= "0.0.0-unstable"}

[[module]]
name = "wasm2wat"
source = "out/wasi/wasm2wat.wasm"
abi = "wasi"
interfaces = {wasi= "0.0.0-unstable"}

[[module]]
name = "wasm-interp"
source = "out/wasi/wasm-interp.wasm"
abi = "wasi"
interfaces = {wasi= "0.0.0-unstable"}

[[module]]
name = "wasm-validate"
source = "out/wasi/wasm-validate.wasm"
abi = "wasi"
interfaces = {wasi= "0.0.0-unstable"}

[[module]]
name = "wasm-strip"
source = "out/wasi/wasm-strip.wasm"
abi = "wasi"
interfaces = {wasi= "0.0.0-unstable"}

# The commands for each module
[[command]]
name = "wat2wasm"
module = "wat2wasm"

[[command]]
name = "wast2json"
module = "wast2json"

[[command]]
name = "wasm2wat"
module = "wasm2wat"

[[command]]
name = "wasm-interp"
module = "wasm-interp"

[[command]]
name = "wasm-validate"
module = "wasm-validate"

[[command]]
name = "wasm-strip"
module = "wasm-strip"
